on-unmatched = "debug"

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.black]
command = "black"
includes = ["*.py"]
priority = 0

[formatter.isort]
command = "isort"
includes = ["*.py"]
priority = 1

[formatter.robocop]
command = "robocop"
options = ["format"]
includes = ["*.robot"]
